additional_ports: {}
additional_ports_only: false
connect_verbose_info: 0
dns_ipv6: false
fast_open: false
local_port: 1080
log:
  level: "0"
  log_file: ""
method: chacha20-ietf
obfs: plain
obfs_param: cdn.sharepointonline.com
password: pass
protocol: auth_aes128_md5
protocol_param: xxxx
redirect: ""
server:
- ss_provider_ips
server_port: 1020
speed_limit_per_con: 0
speed_limit_per_user: 0
timeout: 60
udp_timeout: 60
